"""Shared constants."""

ACTION_EXPAND_PARENT = "expand_parent"
ACTION_SUMMARIZE_ROUTE = "summarize_route"
ACTION_CONFIRM_TARGET = "confirm_target"

MODE_EXPLORED_ONLY = "explored_only"

ERR_INVALID_INPUT = "INVALID_INPUT"
ERR_STATE_CONFLICT = "STATE_CONFLICT"
ERR_UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
ERR_PAL_NOT_FOUND = "PAL_NOT_FOUND"
ERR_ROUTE_TIMEOUT = "ROUTE_TIMEOUT"
