"""Shared constants."""

ACTION_EXPAND_PARENT = "expand_parent"
ACTION_CONFIRM_TARGET = "confirm_target"
ACTION_SELECT_PARENT_PAIR = "select_parent_pair"
ACTION_CONTINUE_FROM_PARENT = "continue_from_parent"

MODE_EXPLORED_ONLY = "explored_only"

ERR_INVALID_INPUT = "INVALID_INPUT"
ERR_STATE_CONFLICT = "STATE_CONFLICT"
ERR_UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
ERR_PAL_NOT_FOUND = "PAL_NOT_FOUND"
